name: "Build kernel"              
on:
  push:
    branches: main                                   
  workflow_dispatch:                                  
jobs:
  build:
    name: "Build kernel"
    runs-on: ubuntu-18.04
    steps:
    - name: "Checkout kernel source"                  
      uses: actions/checkout@v2
      with:
        repository: "mediatek-android-development/android_kernel_mediatek_mt6761-62-4.9"
    - name: "Checkout zipper"                         
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             
        path: zipper                                  
    - name: "Android kernel build"                    
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   
        compiler: gcc/6                               
        defconfig: k61v1_64_bsp_defconfig                     
        image: Image.gz-dtb                           


